theme: minima
title: myRLS_
author: sriharsha_
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I post everyday the things I learn of a picked up random technology..

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
